estate/contact/urls.py
from django.conf.urls import url

from .import views


urlpatterns = [
	url(r'^$', views.contact, name="contact"),
]

estate/estate/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
#from django.views.generic import TemplateView
from core import views

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.core import urls as wagtail_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('feature/<int:id>/', views.featuredetail, name='featuredetail'),
    path('videos/', include('videos.urls')),
    path('properties/', include('projects.urls')),
    path('about/', views.about, name='about'),
    path('contact/', include('contact.urls')),
    re_path(r'^cms/', include(wagtailadmin_urls)),
    re_path(r'^documents/', include(wagtaildocs_urls)),
    re_path(r'^pages/', include(wagtail_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'OtoLive Homes'

estate/contact/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Contact(models.Model):
        name = models.CharField(max_length=50)
        email = models.EmailField(max_length=50)
        subject =models.CharField(max_length=50)
        message = models.TextField()

        def __str__(self):
                return self.name

estate/projects/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.db.models.signals import pre_save
# from filer.fields.imagefields import FilerImageField
from django.utils import timezone
from django.utils.text import slugify
# Create your models here.


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


class Property(models.Model):
    title = models.CharField(max_length=250)
    state = models.CharField(max_length=250)
    city = models.CharField(max_length=250)
    address = models.CharField(max_length=500)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    image_name = models.CharField(max_length=250, null=True, blank=True)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    draft = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    when = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("update_detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-when", "-updated"]
        verbose_name_plural = 'Properties'


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Property.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Property)


class FeaturedProperty(models.Model):
    title = models.CharField(max_length=500)
    total_price = models.CharField(max_length=250, blank=True, null=True)
    state = models.CharField(max_length=250, blank=True, null=True)
    city = models.CharField(max_length=250, blank=True, null=True)
    address = models.CharField(max_length=500, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    house_image = models.ImageField(
        upload_to=upload_location,
        null=True, blank=True,
        width_field="width_field",
        height_field="height_field")
    floor_image = models.ImageField(
        upload_to=upload_location,
        null=True, blank=True,
        width_field="width_field",
        height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    when = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("featuredetail", kwargs={"id": self.id})

    class Meta:
        ordering = ["-when", "-updated"]
        verbose_name_plural = 'Featured Properties'


class Payment(models.Model):
    title = models.ForeignKey(FeaturedProperty, on_delete=models.CASCADE)
    months = models.PositiveIntegerField(default=12, null=True)
    percentage = models.DecimalField(
        max_digits=12, decimal_places=2, null=True)
    initial_pay = models.DecimalField(
        max_digits=12, decimal_places=2, null=True)
    installment = models.DecimalField(
        max_digits=12, decimal_places=2, null=True)
    balance = models.DecimalField(max_digits=12, decimal_places=2, null=True)
    total_price = models.DecimalField(
        max_digits=12, decimal_places=2, null=True)
    # months = models.CharField(max_length=50, blank=True, null=True)
    # percentage = models.CharField(max_length=250, blank=True, null=True)
    # initial_pay = models.CharField(max_length=250, blank=True, null=True)
    # installment = models.CharField(max_length=250, blank=True, null=True)
    # balance = models.CharField(max_length=250, blank=True, null=True)
    # total_price = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return '{} months {}'.format(self.months, self.title.title)

estate/contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    subject = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    message = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Contact
        fields = [
            'name',
            'email',
            'subject',
            'message',
        ]

estate/contact/views.py
from django.shortcuts import render
from .forms import ContactForm


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        name = form.cleaned_data["name"]
        email = form.cleaned_data["email"]
        subject = form.cleaned_data["subject"]
        message = form.cleaned_data["message"]

        instance.save()

    context = {
        "form": form,
        }
    return render(request, "contact.html", context)

estate/templates/about.html
{% extends "base3.html" %}
{% load staticfiles %}
{% block title %}About Us {% endblock title %}

{% block content %}

<div class=" banner-buying" style=" background: url('/static/images/5.jpg') no-repeat;">
	<div class=" container">
	<h3><span>Abou</span>t Us</h3> 
	<!--feature3.jpeg-->
	<div class="clearfix"> </div>
		<!--initiate accordion-->	
	</div>
</div>
<!--//header built with modern facilities and international architechural standards powered with top notch finishing Each unit comes its unique view and good spacial arrangement OT Olive homes and properties is an urban real estate development, investment and management firm based in Lagos, Nigeria. with the visionary leadership of an exellent team of directors mananaging OT Olive Nigeria Limited, which was incorporated in 2010 having operated in the oil and gas sector, transportation, electronics sector and the microfinance sector.-->

<div class="about">	
	<div class="about-head">
		<div class="container">
			<h3>About Us</h3>
				<div class="about-in">
					<a href=""><img src="{% static 'images/feature2.jpeg' %}" alt="image" class="img-responsive ">	</a>			
					<h6> <a>OT. Olive Homes and Properties</a></h6>
					<p style="text-align: justify;">OT. Olive homes and properties is an urban real estate developement, investment and management firm based in Lagos, Nigeria. With the visionary leadership of an excellent team of directors managing OT Olive Nigeriia Limited, which was incorporated in 2010, having operated in the oil and gas sector, transportation, electronics and the microfinance sector.<br>

                    <br>Based on our passion to provide a quality service that is unique to the industry and deliver a distinct competitive advantage. The property management team aims to achieve high owners satisfaction rates in the industry by providing superior services.</p>
				</div>
		</div>
	</div>
	<!---->
	<div class="about-middle">
		<div class="container">		
			<div class="col-md-8 about-mid">
				<h4>Our goal at OT. Olive Homes and Properties</h4>
				<h6><a>we are determined to capture sustainable opportunities for all of our properties</a> </h6>
                <h6><a>we are focused on quantifiable performance and continous improvements</a> </h6>
                <h6><a>We are commited to doing all the chunck of the work and leaving you to enjoy the benefits</a> </h6>
<!-- 
				<p >Hence we work tiredlesly to ensure that our properties are equiped with <br>
				<ol>
					<li>water Treatment Plant</li>
					<li>Adequate Parking Space for each Duples</li>
					<li>Optional Solar Power Systems</li>
					<li>Remote Automated Gate System</li>
					<li>Quality Tiles and good interior fininshing</li>
					<li>Good Access Roads</li>
					<li>C of O and all necessary documents</li>
				</ol>
				<br> this is all in a bid to capture sustainable opportunities for all our properties.</p>
 -->
			</div>
			<div class="col-md-4 about-mid1">
				<p>Our passion to provide quality service is unique in the industry and delivers a distinct competitive advantage </p>
				<!-- <a href="blog_single.html" class="hvr-sweep-to-right more-in">READ MORE</a> -->
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<!---->
	
<!--service-->
<!-- <div class="services">
    <div class="container">
        <div class="service-top">
            <h3>Join Us Today</h3>
            <p>Our management team has made life easier! <br>Here are few of the benefits packed in stock for you:</p>
        </div>
        <div class="services-grid">
            <div class="col-md-6 service-top1">
                <div class=" ser-grid"> 
                    <a href="#" class="hi-icon hi-icon-archive glyphicon glyphicon-user"> </a>
                </div>
                <div  class="ser-top">
                    <h4>You need a home</h4>
                    <p>Buying your first home can be daunting, but we can show you that it doesn't have to be. In fact buying a new home with us can be quick, easy and fun.
                    We’ll also help you manage your money, find a mortgage and make light work of solicitors, offers, surveys and contracts. So you can move in with the minimum of hassle.
                    <br>
                    <a href="">First Time Buyers Advice > </a> </p>
                </div>
                <div class="clearfix"> </div>
           </div>
            <div class="col-md-6 service-top1">
                <div class=" ser-grid"> 
                    <a href="#" class="hi-icon hi-icon-archive glyphicon glyphicon-leaf"> </a>
                </div>
                <div  class="ser-top">
                    <h4>Growing family</h4>
                    <p>If you’re looking for a home with more space, or just one with a garden, we’ll help you find it fast, and steer clear of time-consuming chains.
                    We’ll also show you how to sell your old home, get a mortgage, understand the legal side and stay organised on the day of the move.<br>
                    <a href="">Find out more > </a></p>
                </div>
                <div class="clearfix"> </div>
            </div>
        <div class="clearfix"> </div>
     </div>
     <div class="services-grid">
            <div class="col-md-6 service-top1">
                <div class=" ser-grid"> 
                    <a href="#" class="hi-icon hi-icon-archive glyphicon glyphicon-cog"> </a>
                </div>
                <div  class="ser-top">
                    <h4>Cutting cost</h4>
                        <p>If you’re looking to reduce your outgoings, free up extra income or just move to a more manageable home, we can help you make a fresh start.From finding a new home, to marketing your old home, we’ll tell you everything you need to know about solicitors, surveys and selling. <br>
                        <a href="">Find out more > </a></p>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="col-md-6 service-top1">
                <div class=" ser-grid"> 
                    <a href="#" class="hi-icon hi-icon-archive glyphicon glyphicon-file"> </a>
                </div>
                <div  class="ser-top">
                    <h4>Investment Opportunities</h4>
                    <p>Whether you are looking to add to your property portfolio or invest in property for the first time, we can help you make the most of your money.From legal advice and assistance with furnishing your property, to help sourcing buy-to-let mortgages, we offer investors and landlords a wide range of services and assistance.<br>
                    <a href="">Find out more > </a></p>
                </div>
                <div class="clearfix"> </div>
            </div>
          <div class="clearfix"> </div>
        </div>
    </div>
</div> -->
<!--//services-->



</div>

{% endblock content %}

estate/templates/contact.html
{% extends "base3.html" %}
{% load staticfiles %}
{% block title %}Contact {% endblock title %}



{% block content %}
 

<div class=" banner-buying">
	<div class=" container">
	<h3><span>Cont</span>act</h3> 
	<!---->
	
	<div class="clearfix"> </div>
		<!--initiate accordion-->
    		
	</div>
</div>
<!--//header-->

<!--contact-->
<div class="contact">
	<div class="container">
		<h3>Contact</h3>
	 <div class="contact-top">
		<div class="col-md-6 contact-top1">
		  <!-- <h4 > Info</h4>
          <p class="text-contact">Our passion to provide quality service is unique in the industry and delivers a distinct competitive advantage. The property management team aims to help owners gain high satisfaction in the industry by providing superior services.<br>Contact us today to know more</p> -->
		  <div class="contact-address">
		  	<div class="col-md-6 contact-address1">
			  	 <h5>Address</h5>
	             <p><b>OT.Olive Homes Nigerian Limited</b></p>
	             <p>3, CMD Road, Off Ikosi Road</p>
	             <p>Magodo, Lagos</p>	
		  	</div>
		  	<div class="col-md-6 contact-address1">
			  	  <h5>Email Address </h5>
	             <p>Email :<a href="malito:info@otolivehomes.com"> info@otolivehomes.com</a></p>
		  	</div>
		  	<div class="clearfix"></div>
		  </div>
		  <div class="contact-address">
		  	<div class="col-md-6 contact-address1">
			  	 <h5 >Phone </h5>
	             <p>Mobile1 : 0818 800 3366</p>
	             <p>Mobile2 : 0818 800 2266</p>
	        </div>
	        <div class="col-md-6 contact-address1">
			  	 <h5 >Website </h5>
	             <p>www.otolivehomes.com</p>	             
	        </div>

		  	<div class="clearfix"></div>
		  </div>
		</div>
		<div class="col-md-6 contact-right">
	
            <form action="" method="POST">{% csrf_token %}
            {% if form.non_field_errors %}
	            {% for error in form.non_field_errors %}
	                <div class="alert alert-danger">
	                    {{ error }}
	                </div>
	            {% endfor %}
	        {% endif %}

	        	<div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                             <label for="id_subject">Subject</label>
                            {{ form.subject.errors }}
                            {{ form.subject }}
                        <!-- <input type="text" class="form-control" placeholder="Subject" id="subject" required data-validation-required-message="Please enter the Subject."> -->
                        <p class="help-block text-danger"></p>
                    </div>
                </div>

                <div class="row control-group">                
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label for="id_name">Name</label>
                            {{ form.name.errors }}
                            {{ form.name }}
                        <!-- <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your Name."> -->
                        <p class="help-block text-danger"></p>
                    </div>
                </div>

                <div class="row control-group">                
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label for="id_name">Email</label>
                            {{ form.email.errors }}
                            {{ form.email }}
                        <!-- <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your Name."> -->
                        <p class="help-block text-danger"></p>
                    </div>
                </div>

                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label for="id_subject">Message</label>
                            {{ form.message.errors }}
                            {{ form.message }}
                        <!-- <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a Message."></textarea> -->
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
 
                <div class="row">
                            <div class="form-group col-xs-12">
                                <button type="submit" class="btn btn-success btn-lg">Send</button>
                            </div>
                        </div>
                
			   <!-- <div class="col-md-6 col-md-offset-3 text-center">
			   <input type="submit" value="Submit">
                    <button type="submit"  class="btn btn-block btn-success ">Send!</button>
               </div> -->
			</form>
		</div>
		<div class="clearfix"> </div>
</div>
	</div>
	<!-- <div class="map">
	     <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3150859.767904157!2d-96.62081048651531!3d39.536794757966845!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1408111832978"> </iframe>
	</div> -->
</div>
<!--//contact-->

{% block extra-js %}
<!-- <script>

  $(function () {

    $('#id_name').attr('placeholder', 'Name');
    $('#id_name').addClass('form-control-feedback');

    $('#id_subject').attr('placeholder', 'Subject');
    $('#id_subject').addClass('form-control');

    $('#id_email').attr('placeholder', 'Email');
    $('#id_email').addClass('form-control');

    $('#id_message').attr('placeholder', 'Message');
    $('#id_message').addClass('form-control');

    $('#id_wallet').attr('placeholder', 'Bitcoin Wallet ID');
    $('#id_wallet').addClass('form-control');

    $('#id_country').attr('placeholder', 'Country');
    $('#id_country').addClass('form-control');

    $('#id_city').attr('placeholder', 'City');
    $('#id_city').addClass('form-control');
    
  });
 
</script>
 -->
<!-- <script type="text/javascript">
     alert('francis');
     alert('the world is a beautiful with ladies')
</script>
 -->
{% endblock extra-js %}
{% endblock content %}

estate/templates/footer.html
{% load staticfiles %}
   <div class="footer">
    <div class="container">
        <div class="footer-top-at">
            <div class="col-md-4">
                <div class="amet-sed" style="width: 100%; text-align: center;">

                <h4>GET IN TOUCH</h4>
                <ul class="nav-bottom">
                    <li>Address: 3 CMD Road, Off Ikosi Road, Magodo Lagos</li>
                    <li>Telephone: 08188003366, 08188002266</li>   
                    <li>
                        <p>Website: <a href="http://otolivehomes.com/">www.otolivehomes.com</a></p>
                        <p>Email: <a href="malito:info@otolivehomes.com">info@otolivehomes.com</a></p>
                    </li>
                    
                </ul> 
                </div>
 
            </div>
            <div class="col-md-8">
                <div class="amet-sed " style="width: 100%;">
                <h4 style="text-align: center;">QUICK CONTACT</h4>
                   
            <form action="{% url 'contact' %}" method="POST">{% csrf_token %}
            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}

                <div class="row control-group">
                <div class="form-group col-md-6 floating-label-form-group controls">
                    <div class="form-group col-md-12 floating-label-form-group controls">
                            <label for="id_name">Email</label>
                            <!-- {{ form.email.errors }} -->
                            <!-- {{ form.email }} -->
                        <input type="text" class="form-control" placeholder="Email" id="Email" required data-validation-required-message="Please enter your Name.">
                        <p class="help-block text-danger"></p>
                    </div>

                    <div class="form-group col-md-12 floating-label-form-group controls">
                             <label for="id_subject">Subject</label>
                            <!-- {{ form.subject.errors }} -->
                            <!-- {{ form.subject }} -->
                        <input type="text" class="form-control" placeholder="Subject" id="subject" required data-validation-required-message="Please enter the Subject.">
                        <p class="help-block text-danger"></p>
                    </div>

                    <div class="form-group col-md-12 floating-label-form-group controls">
                            <label for="id_name">Name</label>
                            <!-- {{ form.name.errors }} -->
                            <!-- {{ form.name }} -->
                        <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your Name.">
                        <p class="help-block text-danger"></p>

                        
                    </div>    
                    
                </div>

                    <div class="form-group col-md-6 floating-label-form-group controls">
                            <label for="id_subject">Message</label>
                            <!-- {{ form.message.errors }} -->
                            <!-- {{ form.message }} -->
                        <textarea rows="10" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a Message."></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                </div>



                <div class="row">
                <!-- <div class="container"> -->
                    <h4 class="grid2" style="text-align: center;">
                        <button type="submit" class="btn btn-success btn-lg">Send</button>
                    </h4> 
                    <!-- </div>                            -->
                </div>
                
               <!-- <div class="col-md-6 col-md-offset-3 text-center">
               <input type="submit" value="Submit">
                    <button type="submit"  class="btn btn-block btn-success ">Send!</button>
               </div> -->
            </form>
            </div>
            </div>

            <!-- <div class="col-md-3 amet-sed ">
                <h4>Property Services</h4>
                   <ul class="nav-bottom">
                        <li><a href="">Residential Property</a></li>
                        <li><a href="">Commercial Property</a></li>
                        <li><a href="">Login</a></li>
                        <li><a href="">Register</a></li>
                        <li><a href="">Short Codes</a></li> 
                    </ul>   
                    <ul class="social">
                        <li><a href=""><i> </i></a></li>
                        <li><a href=""><i class="gmail"> </i></a></li>
                        <li><a href=""><i class="twitter"> </i></a></li>
                        <li><a href=""><i class="camera"> </i></a></li>
                        <li><a href=""><i class="dribble"> </i></a></li>
                    </ul>
            </div> -->
        <div class="clearfix"> </div>
    </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
<!--            <div class="col-md-6 footer-logo">
                <h2 ><a href="{% url 'home' %}">OT. Olive homes</a></h2>
                    <div class="col-md-12  amet-sed" style="text-align: left;">
                         <p>Address: 3 CMD Road, Off Ikosi Road, Magodo Lagos</p>
                        <p>Telephone: 08188003366, 08188002266</p>
                        <p>Website: <a href="http://otolivehomes.com/">www.otolivehomes.com</a></p>
                        <p>Email: <a href="malito:info@otolivehomes.com">info@otolivehomes.com</a></p>
                    </div>
            </div>

  <div class="col-md-5 footer-logo">
                    <div class="col-md-12  amet-sed" style="text-align: center;">
                        <p>Address: 3 CMD Road, Off Ikosi Road, Magodo Lagos</p>
                        <p>Telephone: 08188003366, 08188002266</p>
                        <p>Website: <a href="http://otolivehomes.com/">www.otolivehomes.com</a></p>
                        <p>Email: <a href="malito:info@otolivehomes.com">info@otolivehomes.com</a></p>
                    </div>
            </div> -->

            <div class="footer-class">
                <p  style="text-align: center;">© 2017 <a href="{% url 'home' %}">OT. Olive Homes.</a> All Rights Reserved</p>
                <!-- <p><a href="http://w3layouts.com/" target="_blank">W3layouts Template</a> </p> 
                    <div class="col-md-12  amet-sed" style="text-align: right;">
                         <p>Address: 3 CMD Road, Off Ikosi Road, Magodo Lagos</p>
                        <p>Telephone: 08188003366, 08188002266</p>
                        <p>Website: <a href="http://otolivehomes.com/">www.otolivehomes.com</a></p>
                        <p>Email: <a href="malito:info@otolivehomes.com">info@otolivehomes.com</a></p>
                    </div> -->
            </div>

        <div class="clearfix"> </div>
        </div>
    </div>
</div>